### ISSUE TITLE
Exception when client connects with 0.5.0 release

### ISSUE THREAD

**Issue by kwesterfeld** [capaj/chokidar-socket-emitter#14]
I just tried the 0.5.0 release with my PR merged in, and am having a new issue.  I am starting the server and getting this exception:

```
connected client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
Missing error handler on `socket`.
TypeError: fn is not a function
    at Socket.<anonymous> (/Users/..../ui/node_modules/chokidar-socket-emitter/server.js:66:7)
    at emitTwo (events.js:100:13)
    at Socket.emit (events.js:185:7)
    at Socket.onevent (/Users/..../ui/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/Users/..../ui/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/Users/..../ui/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/..../ui/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/Users/..../ui/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/Users/..../ui/node_modules/socket.io/lib/client.js:175:18)
    at emitOne (events.js:90:13)
```

I wiped my node_modules directory and re-pulled, same issue.  When a client connects, this error occurs.

**Comment by mikz** [comment]
Having the same error.

**Comment by capaj** [comment]
this is fixed in the 0.5.6 of https://github.com/capaj/systemjs-hot-reloader

**Comment by mikz** [comment]
@capaj that does not fix it for me. I am on 0.5.6 already. But it looks like I'm using chokidar-socket-emitter 0.4.6. Will try with 0.5.

edit: It is gone with 0.5.
